/** Original Destroya content. Stable IDs are independent of display spelling.
 * Generated for review from the explicit version-1 functional matrix. */
export const ORIGINAL_CONTENT = {
  contentVersion: 4,
  saveFormatVersion: 3,
  materialDisclaimer:
    'Material names are real. DIME availability, rarity, values, extraction and Destroya Industries processing compatibility are fictional game rules, not real-world mining or market guidance.',
  locations: [
    {
      id: 'loc.l001',
      name: 'Tessick Station',
      category: 'LOCATION',
      role: 'world location',
      description: null,
      zoneCount: 11,
    },
    {
      id: 'loc.l002',
      name: 'Loam Crescent',
      category: 'LOCATION',
      role: 'world location',
      description: null,
      zoneCount: 8,
    },
    {
      id: 'loc.l003',
      name: 'Mica Slope',
      category: 'LOCATION',
      role: 'world location',
      description: null,
      zoneCount: 8,
    },
    {
      id: 'loc.l004',
      name: 'Avenbolt',
      category: 'LOCATION',
      role: 'world location',
      description: null,
      zoneCount: 15,
    },
    {
      id: 'loc.l005',
      name: 'Far Shards',
      category: 'LOCATION',
      role: 'world location',
      description: null,
      zoneCount: 1,
    },
  ],
  zones: [
    {
      id: 'zone.z001',
      name: 'Crew Ring Arrival',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Crew Ring Arrival layout with equivalent services and paired directional exits.',
      location: 'loc.l001',
      width: 30,
      height: 24,
      exits: [
        {
          to: 'zone.z002',
          entry: 'from:zone.z001',
        },
      ],
      objectKinds: ['npc', 'npc'],
      regionCount: 0,
      spawn: [15.5, 12.5],
    },
    {
      id: 'zone.z002',
      name: 'Tessick Concourse',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Tessick Concourse layout with equivalent services and paired directional exits.',
      location: 'loc.l001',
      width: 30,
      height: 24,
      exits: [
        {
          to: 'zone.z001',
          entry: 'from:zone.z002',
        },
        {
          to: 'zone.z003',
          entry: 'from:zone.z002',
        },
        {
          to: 'zone.z006',
          entry: 'from:zone.z002',
        },
        {
          to: 'zone.z010',
          entry: 'from:zone.z002',
        },
      ],
      objectKinds: ['npc', 'npc'],
      regionCount: 0,
      spawn: [15.5, 12.5],
    },
    {
      id: 'zone.z003',
      name: 'Tessick Service Lift',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Tessick Service Lift layout with equivalent services and paired directional exits.',
      location: 'loc.l001',
      width: 30,
      height: 24,
      exits: [
        {
          to: 'zone.z002',
          entry: 'from:zone.z003',
        },
        {
          to: 'zone.z004',
          entry: 'from:zone.z003',
        },
        {
          to: 'zone.z005',
          entry: 'from:zone.z003',
        },
        {
          to: 'zone.z007',
          entry: 'from:zone.z003',
        },
        {
          to: 'zone.z008',
          entry: 'from:zone.z003',
        },
        {
          to: 'zone.z011',
          entry: 'from:zone.z003',
        },
      ],
      objectKinds: ['npc'],
      regionCount: 0,
      spawn: [15.5, 12.5],
    },
    {
      id: 'zone.z004',
      name: 'Tessick Processing Deck',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Tessick Processing Deck layout with equivalent services and paired directional exits.',
      location: 'loc.l001',
      width: 30,
      height: 24,
      exits: [
        {
          to: 'zone.z003',
          entry: 'from:zone.z004',
        },
      ],
      objectKinds: ['refinery', 'npc', 'npc'],
      regionCount: 0,
      spawn: [15.5, 12.5],
    },
    {
      id: 'zone.z005',
      name: 'Tessick Cargo Deck',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Tessick Cargo Deck layout with equivalent services and paired directional exits.',
      location: 'loc.l001',
      width: 30,
      height: 24,
      exits: [
        {
          to: 'zone.z003',
          entry: 'from:zone.z005',
        },
      ],
      objectKinds: ['cargo', 'npc', 'npc'],
      regionCount: 0,
      spawn: [15.5, 12.5],
    },
    {
      id: 'zone.z006',
      name: 'Tessick Exchange',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Tessick Exchange layout with equivalent services and paired directional exits.',
      location: 'loc.l001',
      width: 30,
      height: 24,
      exits: [
        {
          to: 'zone.z002',
          entry: 'from:zone.z006',
        },
      ],
      objectKinds: ['market', 'npc'],
      regionCount: 0,
      spawn: [15.5, 12.5],
    },
    {
      id: 'zone.z007',
      name: 'Tessick Supply Walk',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Tessick Supply Walk layout with equivalent services and paired directional exits.',
      location: 'loc.l001',
      width: 30,
      height: 24,
      exits: [
        {
          to: 'zone.z003',
          entry: 'from:zone.z007',
        },
      ],
      objectKinds: ['equipment', 'npc'],
      regionCount: 0,
      spawn: [15.5, 12.5],
    },
    {
      id: 'zone.z008',
      name: 'Tessick Ship Desk',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Tessick Ship Desk layout with equivalent services and paired directional exits.',
      location: 'loc.l001',
      width: 30,
      height: 24,
      exits: [
        {
          to: 'zone.z003',
          entry: 'from:zone.z008',
        },
        {
          to: 'zone.z009',
          entry: 'from:zone.z008',
        },
      ],
      objectKinds: ['travel', 'npc'],
      regionCount: 0,
      spawn: [15.5, 12.5],
    },
    {
      id: 'zone.z009',
      name: 'Tessick Assigned Bay',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Tessick Assigned Bay layout with equivalent services and paired directional exits.',
      location: 'loc.l001',
      width: 30,
      height: 24,
      exits: [
        {
          to: 'zone.z008',
          entry: 'from:zone.z009',
        },
      ],
      objectKinds: ['travel', 'npc'],
      regionCount: 0,
      spawn: [15.5, 12.5],
    },
    {
      id: 'zone.z010',
      name: 'Tessick Window Walk',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Tessick Window Walk layout with equivalent services and paired directional exits.',
      location: 'loc.l001',
      width: 30,
      height: 24,
      exits: [
        {
          to: 'zone.z002',
          entry: 'from:zone.z010',
        },
      ],
      objectKinds: ['npc'],
      regionCount: 0,
      spawn: [15.5, 12.5],
    },
    {
      id: 'zone.z011',
      name: 'Tessick Service Spine',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Tessick Service Spine layout with equivalent services and paired directional exits.',
      location: 'loc.l001',
      width: 30,
      height: 24,
      exits: [
        {
          to: 'zone.z003',
          entry: 'from:zone.z011',
        },
      ],
      objectKinds: ['npc'],
      regionCount: 0,
      spawn: [15.5, 12.5],
    },
    {
      id: 'zone.z012',
      name: 'Loam First Yard',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Loam First Yard layout with equivalent services and paired directional exits.',
      location: 'loc.l002',
      width: 34,
      height: 26,
      exits: [
        {
          to: 'zone.z014',
          entry: 'from:zone.z012',
        },
        {
          to: 'zone.z018',
          entry: 'from:zone.z012',
        },
        {
          to: 'zone.z013',
          entry: 'from:zone.z012',
        },
        {
          to: 'zone.z019',
          entry: 'from:zone.z012',
        },
      ],
      objectKinds: ['foreman', 'npc', 'market', 'travel'],
      regionCount: 0,
      spawn: [17.5, 13.5],
    },
    {
      id: 'zone.z013',
      name: 'Loam North Yard',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Loam North Yard layout with equivalent services and paired directional exits.',
      location: 'loc.l002',
      width: 34,
      height: 26,
      exits: [
        {
          to: 'zone.z012',
          entry: 'from:zone.z013',
        },
        {
          to: 'zone.z015',
          entry: 'from:zone.z013',
        },
      ],
      objectKinds: ['equipment', 'npc'],
      regionCount: 0,
      spawn: [17.5, 13.5],
    },
    {
      id: 'zone.z014',
      name: 'Loam Survey Terrace',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Loam Survey Terrace layout with equivalent services and paired directional exits.',
      location: 'loc.l002',
      width: 48,
      height: 34,
      exits: [
        {
          to: 'zone.z012',
          entry: 'from:zone.z014',
        },
        {
          to: 'zone.z015',
          entry: 'from:zone.z014',
        },
        {
          to: 'zone.z016',
          entry: 'from:zone.z014',
        },
      ],
      objectKinds: [],
      regionCount: 1,
      spawn: [24.5, 17.5],
    },
    {
      id: 'zone.z015',
      name: 'Loam Cut Trail',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Loam Cut Trail layout with equivalent services and paired directional exits.',
      location: 'loc.l002',
      width: 48,
      height: 34,
      exits: [
        {
          to: 'zone.z014',
          entry: 'from:zone.z015',
        },
        {
          to: 'zone.z013',
          entry: 'from:zone.z015',
        },
        {
          to: 'zone.z017',
          entry: 'from:zone.z015',
        },
      ],
      objectKinds: [],
      regionCount: 1,
      spawn: [24.5, 17.5],
    },
    {
      id: 'zone.z016',
      name: 'Loam Upper Cut',
      category: 'ZONE',
      role: 'extraction tunnel',
      description: 'Original Loam Upper Cut layout with equivalent services and paired directional exits.',
      location: 'loc.l002',
      width: 48,
      height: 34,
      exits: [
        {
          to: 'zone.z014',
          entry: 'from:zone.z016',
        },
        {
          to: 'zone.z017',
          entry: 'from:zone.z016',
        },
      ],
      objectKinds: [],
      regionCount: 1,
      spawn: [24.5, 17.5],
    },
    {
      id: 'zone.z017',
      name: 'Loam Lower Cut',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Loam Lower Cut layout with equivalent services and paired directional exits.',
      location: 'loc.l002',
      width: 48,
      height: 34,
      exits: [
        {
          to: 'zone.z016',
          entry: 'from:zone.z017',
        },
        {
          to: 'zone.z015',
          entry: 'from:zone.z017',
        },
      ],
      objectKinds: [],
      regionCount: 1,
      spawn: [24.5, 17.5],
    },
    {
      id: 'zone.z018',
      name: 'Loam Vehicle Desk',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Loam Vehicle Desk layout with equivalent services and paired directional exits.',
      location: 'loc.l002',
      width: 34,
      height: 26,
      exits: [
        {
          to: 'zone.z012',
          entry: 'from:zone.z018',
        },
      ],
      objectKinds: ['vehicle_terminal'],
      regionCount: 0,
      spawn: [17.5, 13.5],
    },
    {
      id: 'zone.z019',
      name: 'Loam Landing Apron',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Loam Landing Apron layout with equivalent services and paired directional exits.',
      location: 'loc.l002',
      width: 34,
      height: 26,
      exits: [
        {
          to: 'zone.z012',
          entry: 'from:zone.z019',
        },
      ],
      objectKinds: ['travel'],
      regionCount: 0,
      spawn: [17.5, 13.5],
    },
    {
      id: 'zone.z020',
      name: 'Mica East Yard',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Mica East Yard layout with equivalent services and paired directional exits.',
      location: 'loc.l003',
      width: 34,
      height: 26,
      exits: [
        {
          to: 'zone.z022',
          entry: 'from:zone.z020',
        },
        {
          to: 'zone.z021',
          entry: 'from:zone.z020',
        },
        {
          to: 'zone.z026',
          entry: 'from:zone.z020',
        },
        {
          to: 'zone.z027',
          entry: 'from:zone.z020',
        },
      ],
      objectKinds: ['market', 'npc', 'travel'],
      regionCount: 0,
      spawn: [17.5, 13.5],
    },
    {
      id: 'zone.z021',
      name: 'Mica West Yard',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Mica West Yard layout with equivalent services and paired directional exits.',
      location: 'loc.l003',
      width: 34,
      height: 26,
      exits: [
        {
          to: 'zone.z020',
          entry: 'from:zone.z021',
        },
        {
          to: 'zone.z023',
          entry: 'from:zone.z021',
        },
      ],
      objectKinds: ['npc', 'cargo'],
      regionCount: 0,
      spawn: [17.5, 13.5],
    },
    {
      id: 'zone.z022',
      name: 'Mica Shelf Trail',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Mica Shelf Trail layout with equivalent services and paired directional exits.',
      location: 'loc.l003',
      width: 48,
      height: 34,
      exits: [
        {
          to: 'zone.z020',
          entry: 'from:zone.z022',
        },
        {
          to: 'zone.z023',
          entry: 'from:zone.z022',
        },
        {
          to: 'zone.z024',
          entry: 'from:zone.z022',
        },
      ],
      objectKinds: [],
      regionCount: 1,
      spawn: [24.5, 17.5],
    },
    {
      id: 'zone.z023',
      name: 'Mica Ridge Trail',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Mica Ridge Trail layout with equivalent services and paired directional exits.',
      location: 'loc.l003',
      width: 48,
      height: 34,
      exits: [
        {
          to: 'zone.z022',
          entry: 'from:zone.z023',
        },
        {
          to: 'zone.z021',
          entry: 'from:zone.z023',
        },
        {
          to: 'zone.z025',
          entry: 'from:zone.z023',
        },
      ],
      objectKinds: [],
      regionCount: 1,
      spawn: [24.5, 17.5],
    },
    {
      id: 'zone.z024',
      name: 'Mica Upper Tunnel',
      category: 'ZONE',
      role: 'extraction tunnel',
      description: 'Original Mica Upper Tunnel layout with equivalent services and paired directional exits.',
      location: 'loc.l003',
      width: 48,
      height: 34,
      exits: [
        {
          to: 'zone.z022',
          entry: 'from:zone.z024',
        },
        {
          to: 'zone.z025',
          entry: 'from:zone.z024',
        },
      ],
      objectKinds: [],
      regionCount: 1,
      spawn: [24.5, 17.5],
    },
    {
      id: 'zone.z025',
      name: 'Mica Lower Tunnel',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Mica Lower Tunnel layout with equivalent services and paired directional exits.',
      location: 'loc.l003',
      width: 48,
      height: 34,
      exits: [
        {
          to: 'zone.z024',
          entry: 'from:zone.z025',
        },
        {
          to: 'zone.z023',
          entry: 'from:zone.z025',
        },
      ],
      objectKinds: [],
      regionCount: 1,
      spawn: [24.5, 17.5],
    },
    {
      id: 'zone.z026',
      name: 'Mica Vehicle Desk',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Mica Vehicle Desk layout with equivalent services and paired directional exits.',
      location: 'loc.l003',
      width: 34,
      height: 26,
      exits: [
        {
          to: 'zone.z020',
          entry: 'from:zone.z026',
        },
      ],
      objectKinds: ['vehicle_terminal', 'npc'],
      regionCount: 0,
      spawn: [17.5, 13.5],
    },
    {
      id: 'zone.z027',
      name: 'Mica Landing Apron',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Mica Landing Apron layout with equivalent services and paired directional exits.',
      location: 'loc.l003',
      width: 34,
      height: 26,
      exits: [
        {
          to: 'zone.z020',
          entry: 'from:zone.z027',
        },
      ],
      objectKinds: ['travel'],
      regionCount: 0,
      spawn: [17.5, 13.5],
    },
    {
      id: 'zone.z028',
      name: 'Avenbolt Port Hall',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Avenbolt Port Hall layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z030',
          entry: 'from:zone.z028',
        },
        {
          to: 'zone.z029',
          entry: 'from:zone.z028',
        },
        {
          to: 'zone.z042',
          entry: 'from:zone.z028',
        },
      ],
      objectKinds: ['travel', 'npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z029',
      name: 'Avenbolt Assigned Bay',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Avenbolt Assigned Bay layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z028',
          entry: 'from:zone.z029',
        },
      ],
      objectKinds: ['travel', 'npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z030',
      name: 'Avenbolt Port Gate',
      category: 'ZONE',
      role: 'port/service',
      description:
        'Original Avenbolt Port Gate layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z028',
          entry: 'from:zone.z030',
        },
        {
          to: 'zone.z031',
          entry: 'from:zone.z030',
        },
      ],
      objectKinds: ['npc', 'npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z031',
      name: 'Avenbolt Port Platform',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Avenbolt Port Platform layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z030',
          entry: 'from:zone.z031',
        },
        {
          to: 'zone.z032',
          entry: 'from:zone.z031',
        },
      ],
      objectKinds: ['npc', 'npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z032',
      name: 'Avenbolt Loop Car',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Avenbolt Loop Car layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z031',
          entry: 'from:zone.z032',
        },
        {
          to: 'zone.z033',
          entry: 'from:zone.z032',
        },
      ],
      objectKinds: ['npc', 'npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z033',
      name: 'Avenbolt City Platform',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Avenbolt City Platform layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z032',
          entry: 'from:zone.z033',
        },
        {
          to: 'zone.z034',
          entry: 'from:zone.z033',
        },
      ],
      objectKinds: ['npc', 'npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z034',
      name: 'Avenbolt Transit Hall',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Avenbolt Transit Hall layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z033',
          entry: 'from:zone.z034',
        },
        {
          to: 'zone.z035',
          entry: 'from:zone.z034',
        },
        {
          to: 'zone.z041',
          entry: 'from:zone.z034',
        },
      ],
      objectKinds: ['npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z035',
      name: 'Avenbolt Exchange Square',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Avenbolt Exchange Square layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z034',
          entry: 'from:zone.z035',
        },
        {
          to: 'zone.z038',
          entry: 'from:zone.z035',
        },
        {
          to: 'zone.z039',
          entry: 'from:zone.z035',
        },
        {
          to: 'zone.z040',
          entry: 'from:zone.z035',
        },
        {
          to: 'zone.z037',
          entry: 'from:zone.z035',
        },
      ],
      objectKinds: ['npc', 'npc', 'npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z036',
      name: 'Avenbolt Crew Row',
      category: 'ZONE',
      role: 'connected world zone',
      description: 'Original Avenbolt Crew Row layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z037',
          entry: 'from:zone.z036',
        },
        {
          to: 'zone.z040',
          entry: 'from:zone.z036',
        },
      ],
      objectKinds: ['npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z037',
      name: 'Avenbolt Upper Link',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Avenbolt Upper Link layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z035',
          entry: 'from:zone.z037',
        },
        {
          to: 'zone.z036',
          entry: 'from:zone.z037',
        },
      ],
      objectKinds: ['npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z038',
      name: 'Avenbolt Commodity Hall',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Avenbolt Commodity Hall layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z035',
          entry: 'from:zone.z038',
        },
        {
          to: 'zone.z041',
          entry: 'from:zone.z038',
        },
      ],
      objectKinds: ['market', 'npc', 'npc', 'npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z039',
      name: 'Avenbolt Supply Walk',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Avenbolt Supply Walk layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z035',
          entry: 'from:zone.z039',
        },
        {
          to: 'zone.z040',
          entry: 'from:zone.z039',
        },
      ],
      objectKinds: ['equipment', 'npc', 'npc', 'npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z040',
      name: 'Avenbolt Service Lane',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Avenbolt Service Lane layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z035',
          entry: 'from:zone.z040',
        },
        {
          to: 'zone.z039',
          entry: 'from:zone.z040',
        },
        {
          to: 'zone.z036',
          entry: 'from:zone.z040',
        },
        {
          to: 'zone.z041',
          entry: 'from:zone.z040',
        },
      ],
      objectKinds: ['npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z041',
      name: 'Avenbolt Works Quarter',
      category: 'ZONE',
      role: 'connected world zone',
      description:
        'Original Avenbolt Works Quarter layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z040',
          entry: 'from:zone.z041',
        },
        {
          to: 'zone.z038',
          entry: 'from:zone.z041',
        },
        {
          to: 'zone.z034',
          entry: 'from:zone.z041',
        },
      ],
      objectKinds: ['npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z042',
      name: 'Avenbolt Port Cargo',
      category: 'ZONE',
      role: 'port/service',
      description:
        'Original Avenbolt Port Cargo layout with equivalent services and paired directional exits.',
      location: 'loc.l004',
      width: 64,
      height: 42,
      exits: [
        {
          to: 'zone.z028',
          entry: 'from:zone.z042',
        },
      ],
      objectKinds: ['cargo', 'npc', 'npc'],
      regionCount: 0,
      spawn: [32.5, 21.5],
    },
    {
      id: 'zone.z043',
      name: 'Far Shards Claims',
      category: 'ZONE',
      role: 'remote claims',
      description: 'Original Far Shards Claims layout with equivalent services and paired directional exits.',
      location: 'loc.l005',
      width: 30,
      height: 24,
      exits: [],
      objectKinds: ['travel'],
      regionCount: 0,
      spawn: [15.5, 12.5],
    },
  ],
  minerals: [
    {
      id: 'mat.m001',
      name: 'Garnet',
      category: 'GEM',
      role: 'raw hand/vehicle gem',
      description: 'A faceted silicate gem found in compact seam clusters.',
      rawPricePerScu: 130000,
      processedPricePerScu: 0,
      spawnWeights: {
        'extract.x001': 0.5,
        'extract.x002': 0.5,
      },
      extractionClasses: ['HAND_TOOL', 'GROUND_RIG'],
      cargoContainers: ['HAND_HOLD', 'GROUND_RIG_HOLD', 'CARGO_SHIP'],
      refinable: false,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
    },
    {
      id: 'mat.m002',
      name: 'Fluorite',
      category: 'GEM',
      role: 'raw hand/vehicle gem',
      description: 'A translucent gem with flat cleavage faces.',
      rawPricePerScu: 152500,
      processedPricePerScu: 0,
      spawnWeights: {
        'extract.x001': 0.3,
        'extract.x002': 0.3,
      },
      extractionClasses: ['HAND_TOOL', 'GROUND_RIG'],
      cargoContainers: ['HAND_HOLD', 'GROUND_RIG_HOLD', 'CARGO_SHIP'],
      refinable: false,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
    },
    {
      id: 'mat.m003',
      name: 'Spinel',
      category: 'GEM',
      role: 'raw hand/vehicle gem',
      description: 'A hard crystal gem found in deeper pockets.',
      rawPricePerScu: 275000,
      processedPricePerScu: 0,
      spawnWeights: {
        'extract.x001': 0.19,
        'extract.x002': 0.2,
      },
      extractionClasses: ['HAND_TOOL', 'GROUND_RIG'],
      cargoContainers: ['HAND_HOLD', 'GROUND_RIG_HOLD', 'CARGO_SHIP'],
      refinable: false,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
    },
    {
      id: 'mat.m004',
      name: 'Alexandrite',
      category: 'GEM',
      role: 'raw hand/vehicle gem',
      description: 'A rare color-shifting chrysoberyl gem.',
      rawPricePerScu: 17640000,
      processedPricePerScu: 0,
      spawnWeights: {
        'extract.x001': 0.01,
        'extract.x002': 0,
      },
      extractionClasses: ['HAND_TOOL'],
      cargoContainers: ['HAND_HOLD', 'GROUND_RIG_HOLD', 'CARGO_SHIP'],
      refinable: false,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
    },
    {
      id: 'mat.m005',
      name: 'Molybdenite',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A soft metallic ore in thin layered sheets.',
      rawPricePerScu: 1085,
      processedPricePerScu: 2833,
      spawnWeights: {
        'M-Type': 0.3404,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m005.processed',
      processedName: 'Processed Molybdenite',
    },
    {
      id: 'mat.m006',
      name: 'Bauxite',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A granular aluminum-bearing ore rock.',
      rawPricePerScu: 133,
      processedPricePerScu: 349,
      spawnWeights: {
        'E-Type': 0.4444,
        'P-Type': 0.3623,
        'S-Type': 0.289,
        'Q-Type': 0.3676,
        'M-Type': 0.3922,
        'C-Type': 0.3968,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m006.processed',
      processedName: 'Processed Bauxite',
    },
    {
      id: 'mat.m007',
      name: 'Beryl',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A prismatic beryllium-bearing mineral.',
      rawPricePerScu: 1149,
      processedPricePerScu: 2817,
      spawnWeights: {
        'E-Type': 0.2667,
        'S-Type': 0.241,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m007.processed',
      processedName: 'Processed Beryl',
    },
    {
      id: 'mat.m008',
      name: 'Scheelite',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A dense tungsten-bearing mineral.',
      rawPricePerScu: 3080,
      processedPricePerScu: 7983,
      spawnWeights: {
        'E-Type': 0.0976,
        'P-Type': 0.2033,
        'S-Type': 0.1689,
        'Q-Type': 0.1145,
        'M-Type': 0.0426,
        'C-Type': 0.2024,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m008.processed',
      processedName: 'Processed Scheelite',
    },
    {
      id: 'mat.m009',
      name: 'Borax',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A pale borate mineral from evaporite beds.',
      rawPricePerScu: 1416,
      processedPricePerScu: 3634,
      spawnWeights: {
        'Q-Type': 0.2206,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m009.processed',
      processedName: 'Processed Borax',
    },
    {
      id: 'mat.m010',
      name: 'Chalcopyrite',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A copper-iron sulfide ore with a metallic sheen.',
      rawPricePerScu: 153,
      processedPricePerScu: 408,
      spawnWeights: {
        'E-Type': 0.4878,
        'P-Type': 0.3623,
        'S-Type': 0.3012,
        'Q-Type': 0.3584,
        'M-Type': 0.5051,
        'C-Type': 0.3891,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m010.processed',
      processedName: 'Processed Chalcopyrite',
    },
    {
      id: 'mat.m011',
      name: 'Corundum',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A hard aluminum-oxide mineral.',
      rawPricePerScu: 158,
      processedPricePerScu: 389,
      spawnWeights: {
        'E-Type': 0.4717,
        'P-Type': 0.3623,
        'S-Type': 0.3012,
        'Q-Type': 0.3584,
        'M-Type': 0.3891,
        'C-Type': 0.361,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m011.processed',
      processedName: 'Processed Corundum',
    },
    {
      id: 'mat.m012',
      name: 'Native Gold',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'Naturally occurring gold in host rock.',
      rawPricePerScu: 3211,
      processedPricePerScu: 8099,
      spawnWeights: {
        'E-Type': 0.2222,
        'P-Type': 0.0431,
        'S-Type': 0.0685,
        'Q-Type': 0.1145,
        'M-Type': 0.1961,
        'C-Type': 0.0844,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m012.processed',
      processedName: 'Processed Native Gold',
    },
    {
      id: 'mat.m013',
      name: 'Chromite',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A dark chromium-bearing ore mineral.',
      rawPricePerScu: 1122,
      processedPricePerScu: 2830,
      spawnWeights: {
        'C-Type': 0.2888,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m013.processed',
      processedName: 'Processed Chromite',
    },
    {
      id: 'mat.m014',
      name: 'Hematite',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'An iron-oxide ore with red-brown streaks.',
      rawPricePerScu: 161,
      processedPricePerScu: 407,
      spawnWeights: {
        'E-Type': 0.4444,
        'P-Type': 0.4065,
        'S-Type': 0.3378,
        'Q-Type': 0.3817,
        'M-Type': 0.3922,
        'C-Type': 0.3546,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m014.processed',
      processedName: 'Processed Hematite',
    },
    {
      id: 'mat.m015',
      name: 'Sphalerite',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A zinc-bearing sulfide ore.',
      rawPricePerScu: 1173,
      processedPricePerScu: 3115,
      spawnWeights: {
        'P-Type': 0.3125,
        'S-Type': 0.2454,
        'Q-Type': 0.1527,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m015.processed',
      processedName: 'Processed Sphalerite',
    },
    {
      id: 'mat.m016',
      name: 'Native Platinum',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A scarce platinum-group mineral occurrence.',
      rawPricePerScu: 10118,
      processedPricePerScu: 25153,
      spawnWeights: {
        'E-Type': 0.0566,
        'P-Type': 0.0517,
        'S-Type': 0.0411,
        'Q-Type': 0.0458,
        'M-Type': 0.0385,
        'C-Type': 0.0476,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m016.processed',
      processedName: 'Processed Native Platinum',
    },
    {
      id: 'mat.m017',
      name: 'Quartz',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A common silica mineral with varied crystal habits.',
      rawPricePerScu: 160,
      processedPricePerScu: 416,
      spawnWeights: {
        'E-Type': 0.4255,
        'P-Type': 0.431,
        'S-Type': 0.3425,
        'Q-Type': 0.3584,
        'M-Type': 0.4255,
        'C-Type': 0.4219,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m017.processed',
      processedName: 'Processed Quartz',
    },
    {
      id: 'mat.m018',
      name: 'Cassiterite',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A dense tin-oxide ore.',
      rawPricePerScu: 3118,
      processedPricePerScu: 7840,
      spawnWeights: {
        'E-Type': 0.0943,
        'P-Type': 0.1984,
        'S-Type': 0.1634,
        'Q-Type': 0.1075,
        'M-Type': 0.0755,
        'C-Type': 0.1984,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m018.processed',
      processedName: 'Processed Cassiterite',
    },
    {
      id: 'mat.m019',
      name: 'Ilmenite',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A titanium-iron oxide mineral.',
      rawPricePerScu: 194,
      processedPricePerScu: 517,
      spawnWeights: {
        'E-Type': 0.4717,
        'P-Type': 0.3906,
        'S-Type': 0.3268,
        'Q-Type': 0.3817,
        'M-Type': 0.3774,
        'C-Type': 0.4049,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m019.processed',
      processedName: 'Processed Ilmenite',
    },
    {
      id: 'mat.m020',
      name: 'Wolframite',
      category: 'ORE',
      role: 'raw/refinable ship ore',
      description: 'A heavy tungsten-bearing ore mineral.',
      rawPricePerScu: 172,
      processedPricePerScu: 431,
      spawnWeights: {
        'E-Type': 0.4444,
        'P-Type': 0.3968,
        'S-Type': 0.3067,
        'Q-Type': 0.3584,
        'M-Type': 0.3846,
        'C-Type': 0.361,
      },
      extractionClasses: ['SHIP_RIG'],
      cargoContainers: ['SHIP_MINING_HOLD', 'CARGO_SHIP'],
      refinable: true,
      rawSale: true,
      quantityUnit: '0.01 cSCU',
      processedId: 'mat.m020.processed',
      processedName: 'Processed Wolframite',
    },
  ],
  shipsAndVehicles: [
    {
      id: 'fleet.v001',
      name: 'Lark Skiff',
      category: 'SHIP',
      role: 'starter transport',
      description: 'Destroya Industries starter transport platform with a distinct original hull and cabin.',
      capacityCscu: 2400,
      price: null,
      travelSeconds: 40,
      canTravel: true,
      canMine: false,
      cargoRole: true,
      equipmentEligibility: 'none',
    },
    {
      id: 'fleet.v002',
      name: 'Crawl Rig',
      category: 'GROUND_VEHICLE',
      role: 'ground gem miner',
      description: 'Destroya Industries ground gem miner platform with a distinct original hull and cabin.',
      capacityCscu: 80,
      price: 103950,
      travelSeconds: null,
      canTravel: false,
      canMine: true,
      cargoRole: false,
      equipmentEligibility: 'vehicle mining',
    },
    {
      id: 'fleet.v003',
      name: 'Seam Sloop',
      category: 'SHIP',
      role: 'solo ship miner',
      description: 'Destroya Industries solo ship miner platform with a distinct original hull and cabin.',
      capacityCscu: 3200,
      price: 2929500,
      travelSeconds: 55,
      canTravel: true,
      canMine: true,
      cargoRole: false,
      equipmentEligibility: 'ship heads',
    },
    {
      id: 'fleet.v004',
      name: 'Fourbeam Barge',
      category: 'SHIP',
      role: 'crew ship miner',
      description: 'Destroya Industries crew ship miner platform with a distinct original hull and cabin.',
      capacityCscu: 9600,
      price: 8930250,
      travelSeconds: 55,
      canTravel: true,
      canMine: true,
      cargoRole: false,
      equipmentEligibility: 'ship heads',
    },
    {
      id: 'fleet.v005',
      name: 'Cargo Lark',
      category: 'SHIP',
      role: 'light cargo support',
      description:
        'Destroya Industries light cargo support platform with a distinct original hull and cabin.',
      capacityCscu: 4600,
      price: 2116800,
      travelSeconds: 35,
      canTravel: true,
      canMine: false,
      cargoRole: true,
      equipmentEligibility: 'none',
    },
    {
      id: 'fleet.v006',
      name: 'Rail Freighter',
      category: 'SHIP',
      role: 'compact freight',
      description: 'Destroya Industries compact freight platform with a distinct original hull and cabin.',
      capacityCscu: 6400,
      price: 1701000,
      travelSeconds: 55,
      canTravel: true,
      canMine: false,
      cargoRole: true,
      equipmentEligibility: 'none',
    },
    {
      id: 'fleet.v007',
      name: 'Pairhold Carrier',
      category: 'SHIP',
      role: 'medium freight',
      description: 'Destroya Industries medium freight platform with a distinct original hull and cabin.',
      capacityCscu: 6600,
      price: 3118500,
      travelSeconds: 40,
      canTravel: true,
      canMine: false,
      cargoRole: true,
      equipmentEligibility: 'none',
    },
    {
      id: 'fleet.v008',
      name: 'Crate Trawler',
      category: 'SHIP',
      role: 'container freight',
      description: 'Destroya Industries container freight platform with a distinct original hull and cabin.',
      capacityCscu: 9600,
      price: 3543750,
      travelSeconds: 57,
      canTravel: true,
      canMine: false,
      cargoRole: true,
      equipmentEligibility: 'none',
    },
    {
      id: 'fleet.v009',
      name: 'Reach Courier',
      category: 'SHIP',
      role: 'long-range transport',
      description:
        'Destroya Industries long-range transport platform with a distinct original hull and cabin.',
      capacityCscu: 9600,
      price: 10160640,
      travelSeconds: 47,
      canTravel: true,
      canMine: false,
      cargoRole: true,
      equipmentEligibility: 'none',
    },
    {
      id: 'fleet.v010',
      name: 'Slip Carrier',
      category: 'SHIP',
      role: 'fast support transport',
      description:
        'Destroya Industries fast support transport platform with a distinct original hull and cabin.',
      capacityCscu: 11400,
      price: 12285000,
      travelSeconds: 35,
      canTravel: true,
      canMine: false,
      cargoRole: true,
      equipmentEligibility: 'none',
    },
    {
      id: 'fleet.v011',
      name: 'Widebay Carrier',
      category: 'SHIP',
      role: 'expanded freight',
      description: 'Destroya Industries expanded freight platform with a distinct original hull and cabin.',
      capacityCscu: 12000,
      price: 4252500,
      travelSeconds: 45,
      canTravel: true,
      canMine: false,
      cargoRole: true,
      equipmentEligibility: 'none',
    },
    {
      id: 'fleet.v012',
      name: 'Reach Hauler',
      category: 'SHIP',
      role: 'heavy freight',
      description: 'Destroya Industries heavy freight platform with a distinct original hull and cabin.',
      capacityCscu: 17400,
      price: 8043840,
      travelSeconds: 50,
      canTravel: true,
      canMine: false,
      cargoRole: true,
      equipmentEligibility: 'none',
    },
    {
      id: 'fleet.v013',
      name: 'Segment Hauler',
      category: 'SHIP',
      role: 'modular heavy freight',
      description:
        'Destroya Industries modular heavy freight platform with a distinct original hull and cabin.',
      capacityCscu: 57600,
      price: 12474000,
      travelSeconds: 60,
      canTravel: true,
      canMine: false,
      cargoRole: true,
      equipmentEligibility: 'none',
    },
    {
      id: 'fleet.v014',
      name: 'Bayrise Carrier',
      category: 'SHIP',
      role: 'largest freight',
      description: 'Destroya Industries largest freight platform with a distinct original hull and cabin.',
      capacityCscu: 69600,
      price: 18900000,
      travelSeconds: 57,
      canTravel: true,
      canMine: false,
      cargoRole: true,
      equipmentEligibility: 'none',
    },
  ],
  equipment: [
    {
      id: 'gear.e001',
      name: 'Beamline One',
      category: 'EQUIPMENT',
      role: 'starter hand laser',
      description: 'Original starter hand laser fitted to its equivalent equipment slot.',
      slot: 'HAND_TOOL',
      price: null,
      starterQuantity: 1,
      compatibleWith: 'extract.x001',
      toolStats: {
        id: 'gear.e001',
        name: 'Beamline One',
        tier: 1,
        laserPower: 0.18,
        chargeResponse: 0.68,
        stabilityAssistance: 0.12,
        optimalZoneAssistance: 0.04,
        collectionCapability: true,
        rangeTiles: 2.2,
        heatPerSecond: 0.2,
        cooldownPerSecond: 0.35,
        supportedNodeSizes: [1, 2, 3],
        miningType: 'extract.x001',
      },
      headTimingSeconds: null,
      crewReductionSeconds: null,
    },
    {
      id: 'gear.e002',
      name: 'Bedline S1',
      category: 'EQUIPMENT',
      role: 'single-seat ship head',
      description: 'Original single-seat ship head fitted to its equivalent equipment slot.',
      slot: 'SHIP_HEAD',
      price: null,
      starterQuantity: 0,
      compatibleWith: 'fleet.v003',
      toolStats: null,
      headTimingSeconds: 120,
      crewReductionSeconds: null,
    },
    {
      id: 'gear.e003',
      name: 'Bedline S2',
      category: 'EQUIPMENT',
      role: 'crew ship head',
      description: 'Original crew ship head fitted to its equivalent equipment slot.',
      slot: 'SHIP_HEAD',
      price: null,
      starterQuantity: 0,
      compatibleWith: 'fleet.v003',
      toolStats: null,
      headTimingSeconds: 0,
      crewReductionSeconds: null,
    },
    {
      id: 'gear.e004',
      name: 'Steady Arc I',
      category: 'EQUIPMENT',
      role: 'single-seat upgrade head',
      description: 'Original single-seat upgrade head fitted to its equivalent equipment slot.',
      slot: 'SHIP_HEAD',
      price: 12750,
      starterQuantity: 0,
      compatibleWith: 'fleet.v003',
      toolStats: null,
      headTimingSeconds: 90,
      crewReductionSeconds: null,
    },
    {
      id: 'gear.e005',
      name: 'Steady Arc II',
      category: 'EQUIPMENT',
      role: 'crew upgrade head',
      description: 'Original crew upgrade head fitted to its equivalent equipment slot.',
      slot: 'SHIP_HEAD',
      price: 12750,
      starterQuantity: 0,
      compatibleWith: 'fleet.v004',
      toolStats: null,
      headTimingSeconds: 15,
      crewReductionSeconds: null,
    },
    {
      id: 'gear.e006',
      name: 'Fissurepath I',
      category: 'EQUIPMENT',
      role: 'single-seat force head',
      description: 'Original single-seat force head fitted to its equivalent equipment slot.',
      slot: 'SHIP_HEAD',
      price: 57750,
      starterQuantity: 0,
      compatibleWith: 'fleet.v003',
      toolStats: null,
      headTimingSeconds: 60,
      crewReductionSeconds: null,
    },
    {
      id: 'gear.e007',
      name: 'Fissurepath II',
      category: 'EQUIPMENT',
      role: 'crew force head',
      description: 'Original crew force head fitted to its equivalent equipment slot.',
      slot: 'SHIP_HEAD',
      price: 57750,
      starterQuantity: 0,
      compatibleWith: 'fleet.v004',
      toolStats: null,
      headTimingSeconds: 20,
      crewReductionSeconds: null,
    },
    {
      id: 'gear.e008',
      name: 'Coilpath I',
      category: 'EQUIPMENT',
      role: 'single-seat high-output head',
      description: 'Original single-seat high-output head fitted to its equivalent equipment slot.',
      slot: 'SHIP_HEAD',
      price: 108000,
      starterQuantity: 0,
      compatibleWith: 'fleet.v003',
      toolStats: null,
      headTimingSeconds: 45,
      crewReductionSeconds: null,
    },
    {
      id: 'gear.e009',
      name: 'Coilpath II',
      category: 'EQUIPMENT',
      role: 'crew high-output head',
      description: 'Original crew high-output head fitted to its equivalent equipment slot.',
      slot: 'SHIP_HEAD',
      price: 108000,
      starterQuantity: 0,
      compatibleWith: 'fleet.v004',
      toolStats: null,
      headTimingSeconds: 25,
      crewReductionSeconds: null,
    },
    {
      id: 'gear.e010',
      name: 'Deepwell Contractor',
      category: 'EQUIPMENT',
      role: 'crew specialist',
      description: 'Original crew specialist fitted to its equivalent equipment slot.',
      slot: 'CREW',
      price: 250000,
      starterQuantity: 0,
      compatibleWith: 'fleet.v004',
      toolStats: null,
      headTimingSeconds: null,
      crewReductionSeconds: 5,
    },
    {
      id: 'gear.e011',
      name: 'Spanlink Contractor',
      category: 'EQUIPMENT',
      role: 'crew specialist',
      description: 'Original crew specialist fitted to its equivalent equipment slot.',
      slot: 'CREW',
      price: 250000,
      starterQuantity: 0,
      compatibleWith: 'fleet.v004',
      toolStats: null,
      headTimingSeconds: null,
      crewReductionSeconds: 5,
    },
    {
      id: 'gear.e012',
      name: 'Bracepoint Contractor',
      category: 'EQUIPMENT',
      role: 'senior crew specialist',
      description: 'Original senior crew specialist fitted to its equivalent equipment slot.',
      slot: 'CREW',
      price: 500000,
      starterQuantity: 0,
      compatibleWith: 'fleet.v004',
      toolStats: null,
      headTimingSeconds: null,
      crewReductionSeconds: 15,
    },
  ],
  refineryMethods: [
    {
      id: 'process.p001',
      name: 'Bed Sorting A',
      category: 'REFINERY_METHOD',
      role: 'refinable ship-ore processing',
      description: 'Bed Sorting A is an original Destroya process variant with the source profile unchanged.',
      profile: {
        yield: 'Low',
        cost: 'Medium',
        time: 'Short',
      },
      inputEligibility: 'raw ship-mined refinable ore',
      dynamicRates: 'preserve saved refineryRates.yield/cost/time exactly',
      orderFields: 'preserve rawUnits/refinedUnits/cost/createdAt/readyAt',
    },
    {
      id: 'process.p002',
      name: 'Wash Lift A',
      category: 'REFINERY_METHOD',
      role: 'refinable ship-ore processing',
      description: 'Wash Lift A is an original Destroya process variant with the source profile unchanged.',
      profile: {
        yield: 'High',
        cost: 'Low',
        time: 'Long',
      },
      inputEligibility: 'raw ship-mined refinable ore',
      dynamicRates: 'preserve saved refineryRates.yield/cost/time exactly',
      orderFields: 'preserve rawUnits/refinedUnits/cost/createdAt/readyAt',
    },
    {
      id: 'process.p003',
      name: 'Arc Draw A',
      category: 'REFINERY_METHOD',
      role: 'refinable ship-ore processing',
      description: 'Arc Draw A is an original Destroya process variant with the source profile unchanged.',
      profile: {
        yield: 'Medium',
        cost: 'Medium',
        time: 'Short',
      },
      inputEligibility: 'raw ship-mined refinable ore',
      dynamicRates: 'preserve saved refineryRates.yield/cost/time exactly',
      orderFields: 'preserve rawUnits/refinedUnits/cost/createdAt/readyAt',
    },
    {
      id: 'process.p004',
      name: 'Arc Draw B',
      category: 'REFINERY_METHOD',
      role: 'refinable ship-ore processing',
      description: 'Arc Draw B is an original Destroya process variant with the source profile unchanged.',
      profile: {
        yield: 'High',
        cost: 'Medium',
        time: 'Long',
      },
      inputEligibility: 'raw ship-mined refinable ore',
      dynamicRates: 'preserve saved refineryRates.yield/cost/time exactly',
      orderFields: 'preserve rawUnits/refinedUnits/cost/createdAt/readyAt',
    },
    {
      id: 'process.p005',
      name: 'Heat Pass A',
      category: 'REFINERY_METHOD',
      role: 'refinable ship-ore processing',
      description: 'Heat Pass A is an original Destroya process variant with the source profile unchanged.',
      profile: {
        yield: 'Medium',
        cost: 'High',
        time: 'Short',
      },
      inputEligibility: 'raw ship-mined refinable ore',
      dynamicRates: 'preserve saved refineryRates.yield/cost/time exactly',
      orderFields: 'preserve rawUnits/refinedUnits/cost/createdAt/readyAt',
    },
    {
      id: 'process.p006',
      name: 'Bed Sorting B',
      category: 'REFINERY_METHOD',
      role: 'refinable ship-ore processing',
      description: 'Bed Sorting B is an original Destroya process variant with the source profile unchanged.',
      profile: {
        yield: 'Low',
        cost: 'Low',
        time: 'Short',
      },
      inputEligibility: 'raw ship-mined refinable ore',
      dynamicRates: 'preserve saved refineryRates.yield/cost/time exactly',
      orderFields: 'preserve rawUnits/refinedUnits/cost/createdAt/readyAt',
    },
    {
      id: 'process.p007',
      name: 'Heat Pass B',
      category: 'REFINERY_METHOD',
      role: 'refinable ship-ore processing',
      description: 'Heat Pass B is an original Destroya process variant with the source profile unchanged.',
      profile: {
        yield: 'High',
        cost: 'High',
        time: 'Short',
      },
      inputEligibility: 'raw ship-mined refinable ore',
      dynamicRates: 'preserve saved refineryRates.yield/cost/time exactly',
      orderFields: 'preserve rawUnits/refinedUnits/cost/createdAt/readyAt',
    },
    {
      id: 'process.p008',
      name: 'Wash Lift B',
      category: 'REFINERY_METHOD',
      role: 'refinable ship-ore processing',
      description: 'Wash Lift B is an original Destroya process variant with the source profile unchanged.',
      profile: {
        yield: 'Medium',
        cost: 'Low',
        time: 'Medium',
      },
      inputEligibility: 'raw ship-mined refinable ore',
      dynamicRates: 'preserve saved refineryRates.yield/cost/time exactly',
      orderFields: 'preserve rawUnits/refinedUnits/cost/createdAt/readyAt',
    },
    {
      id: 'process.p009',
      name: 'Arc Draw C',
      category: 'REFINERY_METHOD',
      role: 'refinable ship-ore processing',
      description: 'Arc Draw C is an original Destroya process variant with the source profile unchanged.',
      profile: {
        yield: 'Low',
        cost: 'High',
        time: 'Long',
      },
      inputEligibility: 'raw ship-mined refinable ore',
      dynamicRates: 'preserve saved refineryRates.yield/cost/time exactly',
      orderFields: 'preserve rawUnits/refinedUnits/cost/createdAt/readyAt',
    },
  ],
  currency: {
    id: 'currency.c001',
    name: 'shift marks',
  },
  tutorial: {
    id: 'quest.q001',
    name: 'First Contract',
  },
} as const;

export type OriginalMineralId = (typeof ORIGINAL_CONTENT.minerals)[number]['id'];
export type OriginalShipId = (typeof ORIGINAL_CONTENT.shipsAndVehicles)[number]['id'];
export type OriginalEquipmentId = (typeof ORIGINAL_CONTENT.equipment)[number]['id'];
export type OriginalProcessId = (typeof ORIGINAL_CONTENT.refineryMethods)[number]['id'];
export type OriginalZoneId = (typeof ORIGINAL_CONTENT.zones)[number]['id'];
export type OriginalLocationId = (typeof ORIGINAL_CONTENT.locations)[number]['id'];
